#!/bin/sh

BASEDIR=`dirname $0`
JAVADIR=$BASEDIR/../Resources/Java

exec java \
    -XstartOnFirstThread \
    -classpath $JAVADIR/swt-macosx.jar:$JAVADIR/jikan-pro.jar \
    -Djava.library.path=$JAVADIR \
    com.samskivert.jikan.Jikan
